"""empty message

Revision ID: 5eb553240140
Revises: 80d054386f3d
Create Date: 2020-02-15 21:48:23.876069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb553240140'
down_revision = '80d054386f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datarecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseNumber', sa.Integer(), nullable=True),
    sa.Column('hasRecu', sa.String(length=1), nullable=True),
    sa.Column('descriptionName', sa.String(length=60), nullable=True),
    sa.Column('dateAtten', sa.DateTime(), nullable=True),
    sa.Column('ceCo', sa.String(length=12), nullable=True),
    sa.Column('trainingGroup', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('hours', sa.String(length=3), nullable=True),
    sa.Column('days', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('sta', sa.String(length=1), nullable=True),
    sa.Column('anp', sa.Integer(), nullable=True),
    sa.Column('insIni', sa.String(length=3), nullable=True),
    sa.Column('recurrent', sa.String(length=1), nullable=True),
    sa.Column('oneYearExpire', sa.String(length=30), nullable=True),
    sa.Column('twoYearExpire', sa.String(length=30), nullable=True),
    sa.Column('threeYearExpire', sa.String(length=30), nullable=True),
    sa.Column('fourYearExpire', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datarecords')
    # ### end Alembic commands ###
