"""empty message

Revision ID: 80d054386f3d
Revises: bc237bf18804
Create Date: 2020-02-15 21:45:30.676642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80d054386f3d'
down_revision = 'bc237bf18804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrainData')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrainData',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Course', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Hasrec', mysql.VARCHAR(charset='utf8', length=1), nullable=True),
    sa.Column('DescriptionName', mysql.VARCHAR(charset='utf8', length=60), nullable=True),
    sa.Column('DateAtten', mysql.DATETIME(), nullable=True),
    sa.Column('CeCo', mysql.VARCHAR(charset='utf8', length=12), nullable=True),
    sa.Column('TrqiningGroup', mysql.VARCHAR(charset='utf8', length=30), nullable=True),
    sa.Column('Name', mysql.VARCHAR(charset='utf8', length=40), nullable=True),
    sa.Column('Recurrent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('OneYearExpire', mysql.DATETIME(), nullable=True),
    sa.Column('TwoYearExpire', mysql.DATETIME(), nullable=True),
    sa.Column('ThreeYearExpire', mysql.DATETIME(), nullable=True),
    sa.Column('FourYearExpire', mysql.DATETIME(), nullable=True),
    sa.Column('Sta', mysql.VARCHAR(charset='utf8', length=1), nullable=True),
    sa.Column('AandP', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
