"""empty message

Revision ID: bc237bf18804
Revises: 
Create Date: 2019-12-21 21:55:50.442145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc237bf18804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_table',
    sa.Column('courseNumber', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('descriptionName', sa.String(length=60), nullable=True),
    sa.Column('dataType', sa.String(length=10), nullable=True),
    sa.Column('recurrent', sa.String(length=1), nullable=True),
    sa.Column('hours', sa.String(length=3), nullable=True),
    sa.Column('days', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('companyTrainer', sa.String(length=6), nullable=True),
    sa.Column('sta', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('courseNumber')
    )
    op.create_table('train_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseNumber', sa.Integer(), nullable=True),
    sa.Column('hasRecu', sa.String(length=1), nullable=True),
    sa.Column('descriptionName', sa.String(length=60), nullable=True),
    sa.Column('dateAtten', sa.DateTime(), nullable=True),
    sa.Column('ceCo', sa.String(length=12), nullable=True),
    sa.Column('trainingGroup', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('hours', sa.String(length=3), nullable=True),
    sa.Column('days', sa.Float(precision=7, asdecimal=2), nullable=True),
    sa.Column('sta', sa.String(length=1), nullable=True),
    sa.Column('anp', sa.Integer(), nullable=True),
    sa.Column('insIni', sa.String(length=3), nullable=True),
    sa.Column('recurrent', sa.String(length=1), nullable=True),
    sa.Column('oneYearExpire', sa.DateTime(), nullable=True),
    sa.Column('twoYearExpire', sa.DateTime(), nullable=True),
    sa.Column('threeYearExpire', sa.DateTime(), nullable=True),
    sa.Column('fourYearExpire', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseNumber', sa.Integer(), nullable=True),
    sa.Column('hasRecu', sa.String(length=1), nullable=True),
    sa.Column('dateAtten', sa.DateTime(), nullable=True),
    sa.Column('ceCo', sa.String(length=12), nullable=True),
    sa.Column('trainingGroup', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('sta', sa.String(length=1), nullable=True),
    sa.Column('anp', sa.Integer(), nullable=True),
    sa.Column('InstrutorInitials', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('avatar', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('training_data')
    op.drop_table('train_data')
    op.drop_table('course_table')
    # ### end Alembic commands ###
